#!/usr/bin/env bash
rofi_command="rofi -theme $ROFI_ROOT/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown='󰤆'
reboot='󰜉'
lock='󰌾'
suspend='󰤄'
logout='󰗼'
yes='󰗠'
no='󰅙'

# Confirmation CMD
confirm_cmd() {
    rofi -dmenu \
        -p 'Confirmation' \
        -mesg 'Are you Sure?' \
        -theme "$ROFI_ROOT/confirm.rasi"
}

# Ask for confirmation
confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
"$shutdown")
    ans=$(confirm_exit)
    if [[ "$ans" == "$yes" ]]; then
        systemctl poweroff
    else
        exit
    fi
    ;;
"$reboot")
    ans=$(confirm_exit)
    if [[ "$ans" == "$yes" ]]; then
        systemctl reboot
    else
        exit
    fi
    ;;
"$lock")
    "$SCRIPT_ROOT/screenlock"
    ;;
"$suspend")
    ans=$(confirm_exit)
    if [[ "$ans" == "$yes" ]]; then
        mpc -q pause
        "$SCRIPT_ROOT/screenlock"
        systemctl suspend
    else
        exit
    fi
    ;;
"$logout")
    ans=$(confirm_exit)
    if [[ "$ans" == "$yes" ]]; then
        hyprctl dispatch exit
    else
        exit
    fi
    ;;
esac
