# Monitor
monitorv2 {
    output = desc:ViewSonic Corporation VX2728-FHD X2E233400769
    mode = 1920x1080@165
    position = 0x0
    scale = 1
    supports_wide_color = true
    supports_hdr = true
    vrr = 1
}

# Misc
misc {
    vfr = true
}

# ibus
exec-once = fcitx5

# RMPC setup
bind=SUPER ALT, M, exec, foot --app-id=music rmpc
windowrule = match:class music, float on
windowrule = match:class music, size 1600 800

# ScreenShot util
bind=CTRL, PRINT, exec, grim -g "$(slurp)" "$HOME/screenshots/$(date +'%Y.%m.%d-%H.%M.%S.screenshot.select.png')"

# Player
bind=SUPER, SPACE, global, caelestia:mediaToggle

# vim: ft=hyprlang
