#!/usr/bin/env bash

DEV="${1}"

parted -s -a optimal -- "${DEV}" \
    mklabel gpt \
    mkpart NIXEFI fat32 1MiB 1GiB \
    mkpart nixos btrfs 1GiB 100% \
    set 1 esp on

mkfs.vfat -F 32 -n NIXEFI "${DEV}1"
mkfs.btrfs -L nixos "${DEV}2"

mkdir -p /mnt

mount /dev/disk/by-label/nixos /mnt
btrfs subvolume create /mnt/root
btrfs subvolume create /mnt/home
btrfs subvolume create /mnt/nix
btrfs subvolume create /mnt/swap
umount /mnt

mount -o compress=zstd,subvol=root /dev/disk/by-label/nixos /mnt
mkdir -p /mnt/home /mnt/nix /mnt/swap
mount -o compress=zstd,subvol=home /dev/disk/by-label/nixos /mnt/home
mount -o compress=zstd,noatime,subvol=nix /dev/disk/by-label/nixos /mnt/nix
mount -o noatime,subvol=swap /dev/disk/by-label/nixos /mnt/swap
btrfs filesystem mkswapfile --size 4g --uuid clear /mnt/swap/swapfile

mkdir -p /mnt/boot
mount /dev/disk/by-label/NIXEFI /mnt/boot
