#!/bin/sh

case "$1" in
"select")
    geo=$(slurp)
    grim -g "$geo" "$HOME/screenshots/$(date +'%Y.%m.%d-%H.%M.%S.screenshot.select.png')"
    ;;
*)
    grim "$HOME/screenshots/$(date +'%Y.%m.%d-%H.%M.%S.screenshot.png')"
    ;;
esac
